apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: ingress
images:
  - name: ilmastokompassi/backend
    newName: docker.io/ilmastokompassi/backend
    newTag: latest
  - name: ilmastokompassi/frontend
    newName: docker.io/ilmastokompassi/frontend
    newTag: latest
