apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - imagestreams.yaml
patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: ingress
  - path: add-backend-imagestream-trigger.yaml
    target:
      kind: Deployment
      name: backend
  - path: add-frontend-imagestream-trigger.yaml
    target:
      kind: Deployment
      name: frontend
images:
  - name: ilmastokompassi/backend
    newTag: latest
  - name: ilmastokompassi/frontend
    newTag: latest
