services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    depends_on:
      - dev-db
    env_file:
      - ./backend/.env.dev

  dev-db:
    image: bitnami/postgresql:14
    container_name: dev-db
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend/migrations:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 4s
      timeout: 3s
      retries: 5

volumes:
  postgres-data: