FROM python:3.10-bookworm

RUN pip install poetry==1.6.1

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root && rm -rf $POETRY_CACHE_DIR

RUN apt-get update && \
    apt-get install -y libpq-dev gcc postgresql-client

ENV VIRTUAL_ENV=/app/.venv \
    PATH="/app/.venv/bin:$PATH"

COPY . .

# Enables hot-reload
ENV FLASK_DEBUG=1

EXPOSE 5000

CMD ["invoke", "dev"]