apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: backend
          image: ilmastokompassi/backend
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 300Mi
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: ilmastokompassi-backend-config
                  key: DATABASE_URI
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ilmastokompassi-backend-config
                  key: SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    tier: backend
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    tier: backend
