name: CI/CD - Backend

on:
  release:
    types: [published]
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

concurrency:
  # New commits cancel previous builds only on pull requests. This is because `github.head_ref`` is only set on pull requests and `github.sha`` is unique for each commit.
  group: backend-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ilmastokompassi-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    env:
      DATABASE_URI: postgresql://postgres:postgres@localhost:5432/ilmastokompassi-test
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry==1.6.1
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
          cache-dependency-path: ./backend/poetry.lock
      - run: poetry install
      - run: poetry run invoke lint
      - run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends postgresql-client
      - name: Run DB migrations
        run: |
          psql -d $DATABASE_URI < src/schema.sql
          psql -d $DATABASE_URI < src/climateprofiles.sql
          psql -d $DATABASE_URI < src/questions.sql
      - name: Run tests
        run: poetry run coverage run --branch -m pytest
  deploy-backend:
    needs: build-and-test-backend
    runs-on: ubuntu-latest
    environment: staging
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ilmastokompassi/backend
          flavor: latest=true
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Push backend to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./backend
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
