name: CI/CD - Backend

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
          cache-dependency-path: ./backend/poetry.lock
      - run: pip install poetry==1.6.1
      - run: poetry install
      - run: poetry run invoke lint
      - name: Run tests
        run: poetry run coverage run --branch -m pytest
  deploy-backend:
    needs: build-and-test-backend
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ilmastokompassi/backend
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Push backend to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./backend
          repository: ilmastokompassi/backend
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}