name: CI/CD - Frontend

on:
  release:
    types: [published]
  push:
    branches: [main]
    paths:
      - "frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ilmastokompassi/frontend

concurrency:
  # New commits cancel previous builds only on pull requests. This is because `github.head_ref`` is only set on pull requests and `github.sha`` is unique for each commit.
  group: frontend-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run test
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: staging
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: latest=true
      - name: Login to ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push frontend to ${{ env.REGISTRY }}
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./frontend
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
