name: CI/CD - Frontend

on:
  release:
    types: [published]
  push:
    branches: [main]
    paths:
      - "frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"

concurrency:
  # New commits cancel previous builds only on pull requests. This is because `github.head_ref`` is only set on pull requests and `github.sha`` is unique for each commit.
  group: frontend-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run test
  deploy-frontend:
    needs: build-and-test-frontend
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ilmastokompassi/frontend
          flavor: latest=true
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Push frontend to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./frontend
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
