name: CI/CD - Frontend

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  build-and-test-frontend:
   runs-on: ubuntu-latest
   defaults:
     run:
       working-directory: frontend
   steps:
     - uses: actions/checkout@v3
     - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
         node-version: 18
         cache: "npm"
     - run: npm ci
     - run: npm run lint
  deploy-frontend:
    needs: build-and-test-frontend
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ilmastokompassi/frontend
      - name: Push frontend to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./frontend
          repository: ilmastokompassi/frontend
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  