name: CI

on:
  push:
    branches: [main]
    # paths:
    #   - "**.py"
    #   - "**.js"
    #   - "**.jsx"
  pull_request:
    branches: [main]
    # paths:
    #   - "**.py"
    #   - "**.js"
    #   - "**.jsx"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry 1.6.1
        run: pip install poetry==1.6.1
      - name: Change directory to backend and install dependencies
        run: |
          cd backend
          poetry install
      - name: Run lint
        run: |
          cd backend
          poetry run invoke lint
      - name: Run tests
        run: |
          cd backend
          poetry run coverage run --branch -m pytest
      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "lts/Hydrogen"
      - name: Install JavaScript dependencies
        run: |
          cd frontend
          npm install
      - name: Run JavaScript lint
        run: |
          cd frontend
          npm run lint
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: to dockerhub
        uses: docker/build-push-action@v1.1.0
        with:
          repository: ilmastokompassi/backend
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          tags: staging
          dockerfile: ./backend/Dockerfile
